//write array of 100 jokes in javaScript

const jokes = [
    `Q: What did the fish say when he hit the wall?${/n} A: Dam!`,
    `Q: What did the grape do when he got stepped on?${/n}${/n} A: He let out a little wine!`,
    `Q: What did the 0 say to the 8?${/n} A: Nice belt!`,
    `Q: What did the judge say when the skunk walked into the court room?${/n} A: Odor in the court!`,
    `Q: What did the duck say when he bought lipstick?${/n} A: Put it on my bill!`,
    `Q: What did the tree say to autumn?${/n} A: Leaf me alone!`,
    `Q: What did the butcher say to the cow?${/n} A: You're a little behind on your payments!`,
    `Q: What did the paper say to the pencil?${/n} A: You better write this down!`,
    `Q: What did the bee say to the flower?${/n} A: I'm just buzzing by!`,
    `Q: What did the mayonnaise say?${/n} A: I'm dressed to impress!`,
    `Q: What did the picture say to the wall?${/n} A: I've been framed!`,
    `Q: What did the hat say to the scarf?${/n} A: You go ahead, I'll hang around!`,
    `Q: What did the hat say to the dress?${/n} A: You look stunning!`,
    `Q: What did the frog say when he saw the fly?${/n} A: Time for lunch!`,
    `Q: What did the tie say to the hat?${/n} A: You go on a head!`,
    `Q: What did the policeman say to his belly button?${/n} A: You're under a vest!`,
    `Q: What did the doctor say to the patient?${/n} A: I'm here to check your pulse!`,
    `Q: What did the tie say to the shirt?${/n} A: You go ahead, I'll just hang around!`,
    `Q: What did the ghost say to the other ghost?${/n} A: Do you believe in people?${/n}`,
    `Q: What did the ocean say to the beach?${/n} A: Nothing, it just waved!`,
    `Q: What did the calendar say to April?${/n} A: I'm looking forward to May!`,
    `Q: What did the pirate say when he turned 80?${/n} A: Aye matey!`,
    `Q: What did the pencil sharpener say to the pencil?${/n} A: Stop going in circles and get to the point!`,
    `Q: What did the cheese say when it looked in the mirror?${/n} A: Halloumi!`,
    `Q: What did the light bulb say to the switch?${/n} A: You turn me on!`,
    `Q: What did the traffic light say to the car?${/n} A: Don't look, I'm changing!`,
    `Q: What did the fish say when it hit the wall?${/n} A: Dam!`,
    `Q: What did the pizza say to the chef?${/n} A: You knead me!`,
    `Q: What did the book say to the author?${/n} A: Write on!`,
    `Q: What did the postman say to the mail?${/n} A: I'll take it from here!`,
    `Q: What did the hammer say to the nail?${/n} A: Don't worry, I've got you covered!`,
    `Q: What did the banana say to the monkey?${/n} A: What's up, Chimp?${/n}`,
    `Q: What did the clock say to the wall?${/n} A: It's about time!`,
    `Q: What did the bee say to the flower?${/n} A: Bee mine!`,
    `Q: What did the tree say to the wind?${/n} A: Leaf me alone!`,
    `Q: What did the computer say to the programmer?${/n} A: Type your command!`,
    `Q: What did the paper clip say to the stack of papers?${/n} A: I'm holding it all together!`,
    `Q: What did the calculator say to the student?${/n} A: You can count on me!`,
    `Q: What did the glue say to the paper?${/n} A: We stick together!`,
    `Q: What did the rock say to the gravel?${/n} A: Don't worry, I've got your back!`,
    `Q: What did the hammer say to the screw?${/n} A: Hang in there!`,
    `Q: What did the candle say to the moth?${/n} A: I'm your light!`,
    `Q: What did the pillow say to the bed?${/n} A: I'm all ears!`,
    `Q: What did the ball say to the bat?${/n} A: You better hit me out of the park!`,
    `Q: What did the key say to the lock?${/n} A: You can count on me!`,
    `Q: What did the nail say to the hammer?${/n} A: Give me a hit!`,
    `Q: What did the paper say to the pencil?${/n} A: Write on!`,
    `Q: What did the tree say to the lumberjack?${/n} A: Timber!`,
    `Q: What did the umbrella say to the rain?${/n} A: You can't break me!`,
    `Q: What did the paperclip say to the magnet?${/n} A: I'm no pushover!`,
    `Q: What did the moon say to the stars?${/n} A: Shine on!`,
    `Q: What did the stamp say to the envelope?${/n} A: Stick with me!`,
    `Q: What did the camera say to the photographer?${/n} A: Say cheese!`,
    `Q: What did the bee say to the flower?${/n} A: Buzz off!`,
    `Q: What did the fan say to the wind?${/n} A: Blow me away!`,
    `Q: What did the window say to the curtains?${/n} A: I've got you covered!`,
    `Q: What did the ink say to the pen?${/n} A: Let's get writing!`,
    `Q: What did the mouse say to the computer?${/n} A: I'm plugged in!`,
    `Q: What did the pig say to the farmer?${/n} A: Let's make bacon!`,
    `Q: What did the tomato say to the salad?${/n} A: I'm on top!`,
    `Q: What did the clock say to the wall?${/n} A: It's about time!`,
    `Q: What did the paper say to the scissors?${/n} A: You cut me out!`,
    `Q: What did the snowman say to the snowblower?${/n} A: Chill out!`,
    `Q: What did the bed say to the blanket?${/n} A: Don't worry, I've got you covered!`,
    `Q: What did the hat say to the scarf?${/n} A: I'm just here for the ride!`,
    `Q: What did the broom say to the dustpan?${/n} A: Let's get sweeping!`,
    `Q: What did the tree say to the wind?${/n} A: Branches be crazy!`,
    `Q: What did the stop sign say to the car?${/n} A: Don't look, I'm changing!`,
    `Q: What did the baseball glove say to the baseball?${/n} A: Catch ya later!`,
    `Q: What did the hammer say to the nail?${/n} A: I'm gonna hit the spot!`,
    `Q: What did the zipper say to the jacket?${/n} A: I'm closing in!`,
    `Q: What did the knife say to the butter?${/n} A: I'm spreading the word!`,
    `Q: What did the coffee say to the cup?${/n} A: I'm all brewed up!`,
    `Q: What did the calculator say to the student?${/n} A: Let me crunch the numbers!`,
    `Q: What did the pig say to the farmer?${/n} A: You can't hog all the credit!`,
    `Q: What did the fire say to the match?${/n} A: You light up my life!`,
    `Q: What did the bee say to the flower?${/n} A: Pollinate this!`,
    `Q: What did the flower say to the bee?${/n} A: Bee my guest!`,
    `Q: What did the eraser say to the pencil?${/n} A: Ready for a rub out?${/n}`,
    `Q: What did the anchor say to the boat?${/n} A: You can count on me!`,
    `Q: What did the paper say to the pen?${/n} A: Get writing!`,
    `Q: What did the fork say to the spoon?${/n} A: Let's get a move on!`,
    `Q: What did the snowman say to the snowblower?${/n} A: I'm snow glad to meet you!`,
    `Q: What did the hammer say to the nail?${/n} A: Don't worry, I've got you nailed down!`,
    `Q: What did the paintbrush say to the wall?${/n} A: I'm going to make a statement!`,
    `Q: What did the saw say to the lumber?${/n} A: Let's get cutting!`,
    `Q: What did the blinds say to the window?${/n} A: I'm going to shade things up!`,
    `Q: What did the doctor say to the patient?${/n} A: Take two of these and call me in the morning!`,
    `Q: What did the magnet say to the paperclip?${/n} A: I'm attracted to you!`,
    `Q: What did the clock say to the second hand?${/n} A: Don't rush me!`,
    `Q: What did the ruler say to the pencil?${/n} A: You better measure up!`,
    `Q: What did the mop say to the floor?${/n} A: I'm gonna clean this up!`,
    `Q: What did the battery say to the flashlight?${/n} A: I'm gonna light your way!`,
    `Q: What did the paper say to the pen?${/n} A: Let's get writing!`,
    `Q: What did the hammer say to the nail?${/n} A: I'm gonna hit the spot!`,
    `Q: What did the glue say to the paper?${/n} A: I'll stick with you!`,
    `Q: What did the pencil sharpener say to the pencil?${/n} A: I'm gonna point you in the right direction!`,
    `Q: What did the chef say to the salad?${/n} A: Let's get tossed!`,
    `Q: What did the teacher say to the student?${/n} A: Let's get learning!`,
    `Q: What did the key say to the lock?${/n} A: I'm the only one who fits!`,
    `Q: What did the paintbrush say to the wall?${/n} A: I'm going to make a statement!`,
    `Q: What did the umbrella say to the rain?${/n} A: You can't dampen my spirits!`];

const randomJoke=Math.floor(Math.random()*jokes.length);
// console.log(joke[randomJoke]);
let a=document.getElementById(`jokes`);
a.innerHTML=jokes[randomJoke];




